name: Platzi-Market CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Establecer variable de entorno DB_URL
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
    - name: Establecer variable de entorno DB_USERNAME
      run: |
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
    - name: Establecer variable de entorno DB_PASSWORD
      run: |
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Set up Docker
      uses: docker/setup-qemu-action@v1
    - name: Configure Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: |
        docker build -t alexjuep/platzi-marketv2:latest -f Dockerfile .
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push Docker image
      run: docker push alexjuep/platzi-marketv2:latest
